default: &default
  adapter: postgresql
  database: '<%= ENV['POSTGRESQL_DATABASE'] %>'
  username: '<%= ENV['POSTGRESQL_USERNAME'] %>'
  password: '<%= ENV['POSTGRESQL_PASSWORD'] %>'
  host: '<%= ENV['POSTGRESQL_HOST'] || 'localhost' %>'
  port: '<%= ENV['POSTGRESQL_PORT'] || 5432 %>'
  timeout: 5000

test:
  <<: *default
  database: concord_test

development:
  <<: *default

staging:
  <<: *default

pre_production:
  <<: *default

production:
  <<: *default
  timeout: <%= ENV.fetch('POSTGRESQL_TIMEOUT', 5000).to_i %>
